### ISSUE TITLE
Mysql already installed?

### ISSUE THREAD

**Issue by Alienpruts** [webgriffe/docker-php-apache-base#3]
Hello, 

First off, nice work. I've been able to get everything running, even Xdebug. Well done.

However : there is one thing I'm struggling with ATM : I would be much obliged should you be able to help me.

I'm confused whether MySQL is already installed : I'm trying to log in using the CLI (mysql) command, but I cannot enter using standard root-root user-pwd combo. I then tried installing mysql-server package, but even then I cannot change user credentials for root.

I've checked the Dockerfile / start script, but I only came across the fact that the php extensiosn mysqli / mysqlpdo are installed, so I was wondering if Mysql is installed natively on this image, and if so : how can I retriever root password?

As always, should you require more information, don't hesitate to ask.

**Comment by mmenozzi** [comment]
No MySQL is not installed because it should be on a different container. Docker best practices says that you should have one process per container. So you can use this image for the webserver container and the mysql (or mariadb) official image for the database container.

**Comment by benjaminpick** [comment]
For reference, I have posted the docker compose file that I am using, adapt it to your needs:

https://gist.github.com/benjaminpick/99d30cfa2be6a5b711ff8c1d5844f3c8

Webgriffe has written a good tutorial for this:

http://mmenozzi.github.io/2016/01/22/php-web-development-with-docker/

**Comment by Alienpruts** [comment]
Thank you both for your answers, I already figured as such and went ahead and created a new MySql container. The only thing I struggled with was that in your container the mysql bin was installed (presumably because of the mysqli / pdo OR the mysql client), so whenever I tried calling mysql from the linked container, it would show me the dreaded "Cannot open mysql.. mysql.sock" error message. But as I said, I already managed to make it all work now :) . 

Thanks again.

**Comment by mmenozzi** [comment]
@Alienpruts the mysql bin is the mysql client not server (it would be mysqld bin). The mysql client is installed to allow connection from the webserver container to the database container which is handy in some situations. To do this, from the webserver container, you should enter a command like

    mysql -h <mysql_container_host> -u root -p 

Where <mysql_container_host> is the name used in the links section of your docker compose for the database container.

**Comment by Alienpruts** [comment]
Hello @mmenozzi , 

thank you, I already figured as such (I should update my tickets more often :) ).

Thanks again.

**Comment by mmenozzi** [comment]
No problem @Alienpruts. Have a nice day!
